$ErrorActionPreference = "Stop"

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$src = Join-Path $root "src"
$dist = Join-Path $root "dist"
$entry = Join-Path $root "app.js"
$out = Join-Path $dist "app.bundle.js"

$parts = @(
    "00_app_state.js",
    "05_startup.js",
    "10_core_runtime.js",
    "20_shell.js",
    "30_home.js",
    "40_markets_rewards_more.js",
    "50_sheets.js",
    "60_trade.js",
    "70_components.js",
    "80_interaction.js",
    "90_boot.js"
)

$missing = $parts | Where-Object { !(Test-Path (Join-Path $src $_)) }
if ($missing.Count) {
    throw "Missing web source module(s): $($missing -join ', ')"
}

New-Item -ItemType Directory -Force $dist | Out-Null

$versionSource = [System.IO.File]::ReadAllText((Join-Path $src "50_sheets.js"))
$versionMatch = [regex]::Match($versionSource, 'canvas\d+')
if (!$versionMatch.Success) {
    throw "Cannot detect canvas version from src/50_sheets.js"
}
$version = $versionMatch.Value

$banner = @(
    "// Generated by trust-wallet-pwa/scripts/build-web.ps1.",
    "// Edit files in trust-wallet-pwa/src instead of editing this generated bundle directly.",
    ""
) -join "`r`n"

$body = foreach ($part in $parts) {
    $path = Join-Path $src $part
    $text = [System.IO.File]::ReadAllText($path)
    $text = $text.TrimStart([char]0xFEFF).TrimEnd()
    "// ----- src/$part -----`r`n$text`r`n"
}

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($out, $banner + ($body -join "`r`n"), $utf8NoBom)

$entryText = @(
    "// Web entrypoint. Runtime code is generated from trust-wallet-pwa/src.",
    "// Run trust-wallet-pwa/scripts/build-web.ps1 after editing source modules.",
    "import `"./dist/app.bundle.js?v=$version`";",
    ""
) -join "`r`n"
[System.IO.File]::WriteAllText($entry, $entryText, $utf8NoBom)

Write-Host "Built $out"
Write-Host "Built $entry"
